stages:
  - check-package-json
check-package-json:
  image: python:3.9
  stage: check-package-json
  script:
    |
      git fetch origin main
      git show origin/main:package.json > main_package.json
      git show origin/main:script.py > script.py
      # ls
      python script.py