stages:
  - check-package-json
 
check-package-json:
  stage: check-package-json
  before_script:
    - apt-get update && apt-get install -y jq
  script:
    |
      git fetch origin $CI_COMMIT_BRANCH
      git checkout $CI_COMMIT_BRANCH
      PREVIOUS_PACKAGE_JSON=$(git show origin/$CI_COMMIT_BRANCH~1:package.json)
      CURRENT_PACKAGE_JSON=$(cat package.json)
      PREVIOUS_DEPS=$(echo "$PREVIOUS_PACKAGE_JSON" | jq -r '.dependencies | keys[]')
      CURRENT_DEPS=$(echo "$CURRENT_PACKAGE_JSON" | jq -r '.dependencies | keys[]')
 
      COUNTER=0
      for dep in $PREVIOUS_DEPS; do
        if ! echo "$CURRENT_DEPS" | grep -qw "$dep"; then
          echo "$dep"
          COUNTER=$((COUNTER+1))
        fi
      done
      echo "$COUNTER dendencies are missing"
 
 
      NEW_DEPS=$(comm -13 <(echo "$PREVIOUS_DEPS" | sort) <(echo "$CURRENT_DEPS" | sort))
      if [ -n "$NEW_DEPS" ]; then
        echo "New dependencies added:"
        for dep in $NEW_DEPS; do
          echo "- $dep"
        done
      else
        echo "No modifications have been made to package.json"
      fi
     
      if [ $COUNTER -gt 0 ]; then
      exit 1
      else
        exit 0
      fi